# Generated by Django 4.0.4 on 2022-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
                ('roll', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
